const STORAGE_KEY = 'cyber-adv.scenario-maker.draft.v2';
const COLLECTIONS = {
  characters: { label: '人物', prefix: 'character' }, evidence: { label: '証拠品', prefix: 'evidence' },
  logs: { label: 'ログ', prefix: 'log' }, facts: { label: '判明事項', prefix: 'fact' }, events: { label: 'Event', prefix: 'event' },
  conversations: { label: '会話', prefix: 'conversation' }, hints: { label: 'ヒント', prefix: 'hint' },
};
const $ = (selector) => document.querySelector(selector);
const ui = { tabs: $('#collection-tabs'), list: $('#item-list'), fields: $('#editor-fields'), title: $('#editor-title'), count: $('#item-count'), collectionTitle: $('#collection-title'), preview: $('#json-preview'), validation: $('#validation-list'), toast: $('#toast'), saveState: $('#save-state') };
let scenario; let activeCollection = 'characters'; let selectedIndex = -1; let toastTimer;
const clone = (value) => value === undefined ? undefined : JSON.parse(JSON.stringify(value));
const setOptional = (object, key, value) => value === '' || value === undefined ? delete object[key] : object[key] = value;
const parse = (text, label) => { try { return JSON.parse(text); } catch (error) { throw new Error(`${label}のJSONが正しくありません: ${error.message}`); } };
function blankScenario() { return { schemaVersion: 1, id: 'case_new', title: '新しい事件', defaults: {}, characters: [], evidence: [], logs: [], facts: [], events: [], conversations: [], hints: [] }; }
function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(scenario)); ui.saveState.textContent = '下書きをこのブラウザに保存しました'; } catch { ui.saveState.textContent = '自動保存できませんでした'; } }
function toast(message) { ui.toast.textContent = message; ui.toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => ui.toast.classList.remove('is-visible'), 2000); }
function mutate() { renderList(); renderEditor(); renderPreview(); renderValidation(); persist(); }
function field(parent, label, value, changed, multiline = false, type = 'text') { const wrap = document.createElement('label'); wrap.className = 'field'; wrap.append(document.createTextNode(label)); const input = multiline ? document.createElement('textarea') : document.createElement('input'); input.value = value ?? ''; if (!multiline) input.type = type; input.addEventListener('input', () => changed(input.value, input)); wrap.append(input); parent.append(wrap); return input; }
function select(parent, label, value, options, changed) { const wrap = document.createElement('label'); wrap.className = 'field'; wrap.append(document.createTextNode(label)); const input = document.createElement('select'); for (const option of options) { const el = document.createElement('option'); el.value = option.value; el.textContent = option.label; el.selected = option.value === value; input.append(el); } input.addEventListener('change', () => changed(input.value, input)); wrap.append(input); parent.append(wrap); return input; }
function section(title) { const el = document.createElement('section'); el.className = 'editor-section'; const h = document.createElement('h3'); h.textContent = title; el.append(h); return el; }
function remove(parent, callback) { const button = document.createElement('button'); button.type = 'button'; button.className = 'button danger'; button.textContent = '削除'; button.addEventListener('click', callback); parent.append(button); }
function options(collection) { return [{ value: '', label: '指定なし' }, ...(scenario[collection] || []).map((item) => ({ value: item.id, label: `${item.name || item.title || item.id}（${item.id}）` }))]; }
function condition(parent, label, value, changed) { const box = document.createElement('div'); box.className = 'condition-editor'; const title = document.createElement('div'); title.className = 'field'; title.textContent = label; box.append(title); const check = document.createElement('input'); check.type = 'checkbox'; check.checked = Boolean(value); const text = document.createElement('label'); text.className = 'check-field'; text.append(check, document.createTextNode(' 条件を設定する')); box.append(text); const controls = document.createElement('div'); controls.className = 'field-row'; controls.hidden = !check.checked; box.append(controls); let current = clone(value) || { type: 'fact', targetId: '', operator: 'exists' }; const types = [{ value: 'evidence', label: '証拠' }, { value: 'fact', label: '判明事項' }, { value: 'conversation', label: '会話' }, { value: 'investigation', label: '調査' }, { value: 'logRow', label: 'ログ行' }, { value: 'event', label: 'Event' }]; const targets = () => { if (['evidence', 'fact', 'conversation', 'event'].includes(current.type)) return options({ evidence: 'evidence', fact: 'facts', conversation: 'conversations', event: 'events' }[current.type]); if (current.type === 'investigation') return [{ value: '', label: '指定なし' }, ...(scenario.evidence || []).flatMap((e) => (e.investigations || []).map((x) => ({ value: x.id, label: `${x.label || x.id}（${x.id}）` })))]; return [{ value: '', label: '指定なし' }, ...(scenario.logs || []).flatMap((log) => (log.rows || []).map((x) => ({ value: x.id, label: `${x.text || x.id}（${x.id}）` })))]; }; function draw() { controls.replaceChildren(); select(controls, '種類', current.type, types, (value) => { current.type = value; current.operator = ['evidence', 'fact'].includes(value) ? 'exists' : 'completed'; changed(clone(current)); draw(); }); select(controls, '対象', current.targetId, targets(), (value) => { current.targetId = value; changed(clone(current)); }); select(controls, '演算子', current.operator, [{ value: 'exists', label: '存在する' }, { value: 'completed', label: '完了している' }], (value) => { current.operator = value; changed(clone(current)); }); } check.addEventListener('change', () => { controls.hidden = !check.checked; changed(check.checked ? clone(current) : undefined); }); if (check.checked) draw(); parent.append(box); }
function bind(parent, label, object, key, multiline = false, type = 'text') { field(parent, label, object[key], (value) => { setOptional(object, key, type === 'number' ? (value === '' ? undefined : Number(value)) : value); mutate(); }, multiline, type); }
function renderConversation(item) { const result = []; const basic = section('会話設定'); bind(basic, 'ID', item, 'id'); bind(basic, 'タイトル', item, 'title'); bind(basic, '背景素材', item, 'background'); bind(basic, '完了Event ID', item, 'completionEventId'); condition(basic, '会話の表示条件', item.requires, (value) => { value ? item.requires = value : delete item.requires; mutate(); }); const nodes = item.nodes || (item.nodes = []); select(basic, '開始ノード', item.startNodeId, [{ value: '', label: '選択' }, ...nodes.map((node) => ({ value: node.id, label: node.id }))], (value) => { setOptional(item, 'startNodeId', value); mutate(); }); result.push(basic); const nodesSection = section('会話ノード'); nodes.forEach((node, index) => { const card = document.createElement('div'); card.className = 'nested-card'; bind(card, 'ノードID', node, 'id'); bind(card, '話者ID', node, 'speakerId'); bind(card, 'アイコン素材', node, 'icon'); bind(card, '背景素材', node, 'background'); bind(card, '本文', node, 'text', true); condition(card, 'ノードの表示条件', node.requires, (value) => { value ? node.requires = value : delete node.requires; mutate(); }); select(card, '次のノード', node.nextNodeId, [{ value: '', label: '指定なし（終了）' }, ...nodes.filter((other) => other !== node).map((other) => ({ value: other.id, label: other.id }))], (value) => { setOptional(node, 'nextNodeId', value); if (value) { delete node.choices; delete node.routes; } mutate(); }); renderChoices(card, node, nodes); renderRoutes(card, node, nodes); remove(card, () => { nodes.splice(index, 1); if (item.startNodeId === node.id) delete item.startNodeId; mutate(); }); nodesSection.append(card); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'ノードを追加'; add.addEventListener('click', () => { nodes.push({ id: `node_new_${nodes.length + 1}`, speakerId: 'narrator', text: '' }); if (!item.startNodeId) item.startNodeId = nodes[0].id; mutate(); }); nodesSection.append(add); result.push(nodesSection); return result; }
function renderChoices(parent, node, nodes) { const box = section('選択肢'); const list = node.choices || []; list.forEach((choice, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, '選択肢本文', choice, 'text', true); select(row, '遷移先', choice.nextNodeId, [{ value: '', label: '指定なし' }, ...nodes.map((n) => ({ value: n.id, label: n.id }))], (value) => { setOptional(choice, 'nextNodeId', value); mutate(); }); condition(row, '選択肢の表示条件', choice.requires, (value) => { value ? choice.requires = value : delete choice.requires; mutate(); }); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '選択肢を追加'; add.addEventListener('click', () => { node.choices = list; list.push({ text: '' }); delete node.nextNodeId; delete node.routes; mutate(); }); box.append(add); parent.append(box); }
function renderRoutes(parent, node, nodes) { const box = section('自動分岐（空のノード）'); const list = node.routes || []; list.forEach((route, index) => { const row = document.createElement('div'); row.className = 'nested-card'; condition(row, '分岐条件', route.requires, (value) => { value ? route.requires = value : delete route.requires; mutate(); }); select(row, '次のノード', route.nextNodeId, [{ value: '', label: '選択' }, ...nodes.filter((n) => n !== node).map((n) => ({ value: n.id, label: n.id }))], (value) => { setOptional(route, 'nextNodeId', value); mutate(); }); bind(row, '次の会話ID', route, 'nextConversationId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '分岐を追加'; add.addEventListener('click', () => { node.routes = list; list.push({ nextNodeId: '' }); delete node.nextNodeId; delete node.choices; mutate(); }); box.append(add); parent.append(box); }
function renderSimple(item, collection) { const result = []; const basic = section('基本情報'); bind(basic, 'ID', item, 'id'); if (collection !== 'events') bind(basic, collection === 'conversations' ? 'タイトル' : '表示名', item, collection === 'conversations' ? 'title' : 'name'); if (collection === 'characters') { bind(basic, 'アイコン素材', item, 'icon'); bind(basic, '選択画面の背景', item, 'background'); bind(basic, '役割', item, 'role'); bind(basic, '説明', item, 'description', true); } if (collection === 'evidence') { bind(basic, 'アイコン素材', item, 'icon'); bind(basic, '選択画面の背景', item, 'background'); bind(basic, '説明', item, 'description', true); renderInvestigations(item, basic); } if (collection === 'logs') { bind(basic, '選択画面の背景', item, 'background'); bind(basic, '説明', item, 'description', true); renderRows(item, basic); } if (collection === 'facts') { bind(basic, '説明', item, 'description', true); bind(basic, '表示順', item, 'sortOrder', false, 'number'); } if (collection === 'events') { const trigger = item.trigger || (item.trigger = {}); select(basic, '起動元の種別', trigger.type, [{ value: '', label: '指定なし' }, { value: 'conversation', label: '会話' }, { value: 'investigation', label: '調査' }, { value: 'logRow', label: 'ログ行' }, { value: 'hintStage', label: 'ヒント段階' }], (value) => { setOptional(trigger, 'type', value); mutate(); }); bind(basic, '起動対象ID', trigger, 'targetId'); renderEffects(item, basic); } if (collection === 'hints') { bind(basic, '対象ID', item, 'targetId'); renderStages(item, basic); } result.push(basic); return result; }
function renderInvestigations(item, parent) { const box = section('調査項目'); const list = item.investigations || []; list.forEach((entry, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, 'ID', entry, 'id'); bind(row, '表示名', entry, 'label'); bind(row, '説明', entry, 'description', true); bind(row, '完了Event ID', entry, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '調査項目を追加'; add.addEventListener('click', () => { item.investigations = list; list.push({ id: `investigation_new_${list.length + 1}`, label: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderRows(item, parent) { const box = section('ログ行'); const list = item.rows || (item.rows = []); list.forEach((row, index) => { const card = document.createElement('div'); card.className = 'nested-card'; bind(card, 'ID', row, 'id'); bind(card, '時刻', row, 'time'); bind(card, '本文', row, 'text', true); bind(card, '完了Event ID', row, 'completionEventId'); const check = document.createElement('label'); check.className = 'check-field'; const input = document.createElement('input'); input.type = 'checkbox'; input.checked = Boolean(row.important); input.addEventListener('change', () => { input.checked ? row.important = true : delete row.important; mutate(); }); check.append(input, document.createTextNode(' 調査できる重要行')); card.append(check); remove(card, () => { list.splice(index, 1); mutate(); }); box.append(card); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'ログ行を追加'; add.addEventListener('click', () => { list.push({ id: `row_new_${list.length + 1}`, text: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderEffects(item, parent) { const box = section('Effect'); const list = item.effects || (item.effects = []); list.forEach((effect, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, '種類（add/remove/set）', effect, 'type'); bind(row, '対象ID', effect, 'target'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'Effectを追加'; add.addEventListener('click', () => { list.push({ type: 'add', target: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderStages(item, parent) { const box = section('ヒント段階'); const list = item.stages || (item.stages = []); list.forEach((stage, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, 'ID', stage, 'id'); bind(row, '本文', stage, 'text', true); bind(row, '完了Event ID', stage, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '段階を追加'; add.addEventListener('click', () => { list.push({ id: `hint_stage_new_${list.length + 1}`, text: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderTabs() { ui.tabs.replaceChildren(); Object.entries(COLLECTIONS).forEach(([key, config]) => { const button = document.createElement('button'); button.type = 'button'; button.className = `tab${key === activeCollection ? ' is-active' : ''}`; button.textContent = config.label; button.addEventListener('click', () => { activeCollection = key; selectedIndex = -1; renderTabs(); renderList(); renderEditor(); }); ui.tabs.append(button); }); ui.collectionTitle.textContent = COLLECTIONS[activeCollection].label; }
function renderList() { const items = scenario[activeCollection]; ui.count.textContent = items.length; ui.list.replaceChildren(); items.forEach((item, index) => { const button = document.createElement('button'); button.type = 'button'; button.className = `entry${index === selectedIndex ? ' is-active' : ''}`; button.textContent = item.name || item.title || item.id; button.addEventListener('click', () => { selectedIndex = index; renderList(); renderEditor(); }); ui.list.append(button); }); }
function renderEditor() { const item = scenario[activeCollection][selectedIndex]; ui.fields.replaceChildren(); $('#delete-button').hidden = !item; if (!item) { ui.title.textContent = '項目を選択してください'; ui.fields.innerHTML = '<div class="empty">左の一覧から項目を選ぶか、新しい項目を追加してください。</div>'; return; } ui.title.textContent = item.name || item.title || item.id; try { const sections = activeCollection === 'conversations' ? renderConversation(item) : renderSimple(item, activeCollection); sections.forEach((entry) => ui.fields.append(entry)); } catch (error) { const message = document.createElement('div'); message.className = 'empty'; message.textContent = `編集欄の描画に失敗しました: ${error.message}`; ui.fields.append(message); console.error(error); } }
function renderPreview() { ui.preview.textContent = JSON.stringify(scenario, null, 2); }
function validateScenario() { const errors = []; const warnings = []; if (!scenario.id?.trim()) errors.push('事件IDが空です'); if (!scenario.title?.trim()) errors.push('事件名が空です'); const ids = new Set(); for (const [key, config] of Object.entries(COLLECTIONS)) for (const [index, item] of (scenario[key] || []).entries()) { if (!item?.id) errors.push(`${config.label} ${index + 1} のIDがありません`); else if (ids.has(item.id)) errors.push(`ID「${item.id}」が重複しています`); else ids.add(item.id); if (key !== 'events' && !item.name && !item.title) errors.push(`${config.label}「${item.id || index + 1}」の表示名がありません`); } for (const conversation of scenario.conversations || []) { const nodes = new Set((conversation.nodes || []).map((node) => node.id)); if (!conversation.startNodeId || !nodes.has(conversation.startNodeId)) errors.push(`会話「${conversation.id}」の開始ノードがありません`); for (const node of conversation.nodes || []) { const refs = [node.nextNodeId, ...(node.choices || []).map((choice) => choice.nextNodeId), ...(node.routes || []).map((route) => route.nextNodeId)].filter(Boolean); refs.forEach((ref) => { if (!nodes.has(ref)) errors.push(`ノード「${node.id}」の遷移先「${ref}」がありません`); }); if (node.routes?.length && (node.text || node.speakerId || node.choices || node.nextNodeId)) warnings.push(`ルート専用ノード「${node.id}」には本文・話者・通常遷移を設定しないでください`); } } return { errors, warnings }; }
function renderValidation() { const { errors, warnings } = validateScenario(); ui.validation.replaceChildren(); if (!errors.length && !warnings.length) { const li = document.createElement('li'); li.className = 'ok'; li.textContent = 'エラーはありません。新形式の参照を確認しました。'; ui.validation.append(li); return; } [...errors, ...warnings].forEach((message) => { const li = document.createElement('li'); li.className = errors.includes(message) ? 'error' : ''; li.textContent = `${errors.includes(message) ? 'エラー' : '確認'}：${message}`; ui.validation.append(li); }); }
function addItem() { const config = COLLECTIONS[activeCollection]; const index = scenario[activeCollection].length + 1; const item = { id: `${config.prefix}_new_${String(index).padStart(3, '0')}` }; if (activeCollection === 'characters' || ['evidence', 'logs', 'facts'].includes(activeCollection)) item.name = `新しい${config.label}`; if (activeCollection === 'conversations') { item.title = '新しい会話'; item.nodes = [{ id: 'node_001', speakerId: 'narrator', text: '' }]; item.startNodeId = 'node_001'; } if (activeCollection === 'events') item.effects = []; if (activeCollection === 'hints') item.stages = []; scenario[activeCollection].push(item); selectedIndex = scenario[activeCollection].length - 1; mutate(); }
function download() { const result = validateScenario(); if (result.errors.length) return toast(`エラー ${result.errors.length} 件を修正してください`); const blob = new Blob([`${JSON.stringify(scenario, null, 2)}\n`], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${scenario.id || 'scenario'}.json`; link.click(); URL.revokeObjectURL(link.href); toast('シナリオJSONを書き出しました'); }
async function loadFile(file) { try { scenario = parse(await file.text(), 'ファイル'); if (!scenario || Array.isArray(scenario)) throw new Error('JSONの最上位はオブジェクトにしてください'); Object.keys(COLLECTIONS).forEach((key) => { if (!Array.isArray(scenario[key])) scenario[key] = []; }); activeCollection = 'characters'; selectedIndex = -1; renderAll(); persist(); toast('新形式のJSONを読み込みました'); } catch (error) { toast(error.message); } }
function renderAll() { renderTabs(); renderList(); renderEditor(); $('#case-id').value = scenario.id || ''; $('#case-title').value = scenario.title || ''; $('#case-defaults').value = JSON.stringify(scenario.defaults || {}, null, 2); renderPreview(); renderValidation(); }
$('#case-id').addEventListener('input', (event) => { scenario.id = event.target.value; renderPreview(); renderValidation(); persist(); }); $('#case-title').addEventListener('input', (event) => { scenario.title = event.target.value; renderPreview(); renderValidation(); persist(); }); $('#case-defaults').addEventListener('input', (event) => { try { scenario.defaults = parse(event.target.value, '共通設定'); renderPreview(); persist(); } catch { event.target.setAttribute('aria-invalid', 'true'); } }); $('#add-button').addEventListener('click', addItem); $('#delete-button').addEventListener('click', () => { if (selectedIndex >= 0) { scenario[activeCollection].splice(selectedIndex, 1); selectedIndex = -1; mutate(); } }); $('#download-button').addEventListener('click', download); $('#validate-button').addEventListener('click', () => { renderValidation(); toast('データを検証しました'); }); $('#file-input').addEventListener('change', (event) => { const file = event.target.files?.[0]; if (file) loadFile(file); event.target.value = ''; }); $('#copy-button').addEventListener('click', async () => { try { await navigator.clipboard.writeText(JSON.stringify(scenario, null, 2)); toast('JSONをコピーしました'); } catch { toast('コピーできません。JSONを選択してコピーしてください'); } });
async function start() { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { try { scenario = parse(saved, '保存データ'); } catch { scenario = blankScenario(); } } else { scenario = blankScenario(); const source = new URLSearchParams(location.search).get('source'); if (source) { try { const response = await fetch(`../${encodeURIComponent(source)}`); if (response.ok) scenario = await response.json(); } catch { /* ローカル起動時は空の編集画面を使う */ } } } Object.keys(COLLECTIONS).forEach((key) => { if (!Array.isArray(scenario[key])) scenario[key] = []; }); if (!scenario.defaults || typeof scenario.defaults !== 'object' || Array.isArray(scenario.defaults)) scenario.defaults = {}; scenario.schemaVersion ||= 1; renderAll(); persist(); }
start();
