const STORAGE_KEY = 'cyber-adv.scenario-maker.draft.v2';
const COLLECTIONS = {
  characters: { label: '人物', prefix: 'character' }, evidence: { label: '証拠品', prefix: 'evidence' },
  logs: { label: 'ログ', prefix: 'log' }, facts: { label: '判明事項', prefix: 'fact' },
  events: { label: 'Event', prefix: 'event' }, hints: { label: 'ヒント', prefix: 'hint' },
};
const $ = (selector) => document.querySelector(selector);
const ui = { tabs: $('#collection-tabs'), list: $('#item-list'), outline: $('#outline-list'), outlineTitle: $('#outline-title'), fields: $('#editor-fields'), title: $('#editor-title'), count: $('#item-count'), collectionTitle: $('#collection-title'), preview: $('#json-preview'), jsonDialog: $('#json-dialog'), jsonOpen: $('#json-open-button'), jsonClose: $('#json-close-button'), validation: $('#validation-list'), toast: $('#toast'), saveState: $('#save-state') };
let scenario; let activeCollection = 'characters'; let selectedIndex = -1; let selectedDetail = { type: 'base' }; let toastTimer;
const clone = (value) => value === undefined ? undefined : JSON.parse(JSON.stringify(value));
const setOptional = (object, key, value) => value === '' || value === undefined ? delete object[key] : object[key] = value;
const parse = (text, label) => { try { return JSON.parse(text); } catch (error) { throw new Error(`${label}のJSONが正しくありません: ${error.message}`); } };
function blankScenario() { return { schemaVersion: 1, id: 'case_new', title: '新しい事件', defaults: {}, characters: [], evidence: [], logs: [], facts: [], events: [], hints: [] }; }
function allInteractions() { return (scenario.characters || []).flatMap((character) => (character.interactions || []).map((graph) => ({ character, graph }))); }
function interactionLabel(graph, character) { return `${character.name || character.id}：${graph.title || graph.id}（${graph.id}）`; }
function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(scenario)); ui.saveState.textContent = '下書きをこのブラウザに保存しました'; } catch { ui.saveState.textContent = '自動保存できませんでした'; } }
function toast(message) { ui.toast.textContent = message; ui.toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => ui.toast.classList.remove('is-visible'), 2000); }
function mutate(renderFields = true) { renderList(); renderOutline(); if (renderFields) renderEditor(); renderPreview(); renderValidation(); persist(); }
function field(parent, label, value, changed, multiline = false, type = 'text') { const wrap = document.createElement('label'); wrap.className = 'field'; wrap.append(document.createTextNode(label)); const input = multiline ? document.createElement('textarea') : document.createElement('input'); input.value = value ?? ''; if (!multiline) input.type = type; input.addEventListener('input', () => changed(input.value, input, true)); wrap.append(input); parent.append(wrap); return input; }
function select(parent, label, value, options, changed) { const wrap = document.createElement('label'); wrap.className = 'field'; wrap.append(document.createTextNode(label)); const input = document.createElement('select'); for (const option of options) { const el = document.createElement('option'); el.value = option.value; el.textContent = option.label; el.selected = option.value === value; input.append(el); } input.addEventListener('change', () => changed(input.value, input)); wrap.append(input); parent.append(wrap); return input; }
function section(title) { const el = document.createElement('section'); el.className = 'editor-section'; const h = document.createElement('h3'); h.textContent = title; el.append(h); return el; }
function remove(parent, callback) { const button = document.createElement('button'); button.type = 'button'; button.className = 'button danger'; button.textContent = '削除'; button.addEventListener('click', callback); parent.append(button); }
function moveItem(items, index, direction) { const target = index + direction; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; mutate(); }
function orderButtons(parent, items, index) { const controls = document.createElement('div'); controls.className = 'order-buttons'; for (const [direction, label] of [[-1, '上へ'], [1, '下へ']]) { const button = document.createElement('button'); button.type = 'button'; button.className = 'button secondary order-button'; button.textContent = direction < 0 ? '↑' : '↓'; button.setAttribute('aria-label', label); button.title = label; button.disabled = index + direction < 0 || index + direction >= items.length; button.addEventListener('click', () => moveItem(items, index, direction)); controls.append(button); } parent.append(controls); }
function bind(parent, label, object, key, multiline = false, type = 'text') { field(parent, label, object[key], (value, _input, deferEditor) => { setOptional(object, key, type === 'number' ? (value === '' ? undefined : Number(value)) : value); mutate(!deferEditor); }, multiline, type); }
function options(collection) { return [{ value: '', label: '指定なし' }, ...(scenario[collection] || []).map((item) => ({ value: item.id, label: `${item.name || item.title || item.id}（${item.id}）` }))]; }
function eventOptions() { return options('events'); }
function eventLink(parent, label, object, key) { select(parent, label, object[key] || '', eventOptions(), (value) => { setOptional(object, key, value); mutate(); }); }
function condition(parent, label, value, changed) {
  const box = document.createElement('div'); box.className = 'condition-editor'; const title = document.createElement('div'); title.className = 'field'; title.textContent = label; box.append(title);
  const check = document.createElement('input'); check.type = 'checkbox'; check.checked = Boolean(value); const toggle = document.createElement('label'); toggle.className = 'check-field'; toggle.append(check, document.createTextNode(' 条件を設定する')); box.append(toggle);
  let current = clone(value) || { type: 'fact', targetId: '', operator: 'exists' }; const controls = document.createElement('div'); controls.hidden = !check.checked; box.append(controls);
  const types = [{ value: 'evidence', label: '証拠品' }, { value: 'fact', label: '判明事項' }, { value: 'conversation', label: '会話' }, { value: 'investigation', label: '証拠調査' }, { value: 'logRow', label: 'ログ行' }, { value: 'event', label: 'Event' }];
  const conversationOptions = () => [{ value: '', label: '指定なし' }, ...allInteractions().map(({ character, graph }) => ({ value: graph.id, label: interactionLabel(graph, character) }))];
  const targets = (type) => {
    if (type === 'evidence') return options('evidence'); if (type === 'fact') return options('facts'); if (type === 'event') return options('events'); if (type === 'conversation') return conversationOptions();
    if (type === 'investigation') return [{ value: '', label: '指定なし' }, ...(scenario.evidence || []).flatMap((e) => (e.investigations || []).map((x) => ({ value: x.id, label: `${x.label || x.id}（${x.id}）` })))];
    return [{ value: '', label: '指定なし' }, ...(scenario.logs || []).flatMap((log) => (log.rows || []).map((x) => ({ value: x.id, label: `${x.text || x.id}（${x.id}）` })))];
  };
  const notify = () => changed(clone(current));
  function draw(node, host, depth = 0) {
    if (depth > 16) return; host.replaceChildren(); const card = document.createElement('div'); card.className = 'nested-card'; const kind = ['and', 'or', 'not'].includes(node.type) ? node.type : 'leaf';
    select(card, '条件の形', kind, [{ value: 'leaf', label: '単一条件' }, { value: 'and', label: 'すべて満たす（AND）' }, { value: 'or', label: 'いずれかを満たす（OR）' }, { value: 'not', label: '満たさない（NOT）' }], (next) => { if (next === 'leaf') { node.type = 'fact'; node.targetId = ''; node.operator = 'exists'; delete node.conditions; delete node.condition; } else if (next === 'not') { node.type = 'not'; delete node.conditions; node.condition ||= { type: 'fact', targetId: '', operator: 'exists' }; } else { node.type = next; delete node.condition; node.conditions ||= [{ type: 'fact', targetId: '', operator: 'exists' }]; } notify(); draw(node, host, depth); });
    if (kind === 'leaf') { select(card, '種類', node.type, types, (next) => { node.type = next; node.operator = ['evidence', 'fact'].includes(next) ? 'exists' : 'completed'; node.targetId = ''; notify(); draw(node, host, depth); }); select(card, '対象', node.targetId, targets(node.type), (next) => { node.targetId = next; notify(); }); select(card, '演算子', node.operator, [{ value: 'exists', label: '所持・取得している' }, { value: 'completed', label: '完了している' }], (next) => { node.operator = next; notify(); }); }
    else if (kind === 'not') { const child = document.createElement('div'); card.append(child); draw(node.condition, child, depth + 1); }
    else { const children = document.createElement('div'); children.className = 'condition-children'; (node.conditions || []).forEach((childNode, index) => { const childHost = document.createElement('div'); draw(childNode, childHost, depth + 1); const del = document.createElement('button'); del.type = 'button'; del.className = 'button danger'; del.textContent = '条件を削除'; del.addEventListener('click', () => { node.conditions.splice(index, 1); notify(); draw(node, host, depth); }); childHost.append(del); children.append(childHost); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '子条件を追加'; add.disabled = (node.conditions || []).length >= 16; add.addEventListener('click', () => { node.conditions.push({ type: 'fact', targetId: '', operator: 'exists' }); notify(); draw(node, host, depth); }); card.append(children, add); }
    host.append(card);
  }
  check.addEventListener('change', () => { controls.hidden = !check.checked; changed(check.checked ? clone(current) : undefined); }); if (check.checked) draw(current, controls); parent.append(box);
}
function renderCharacter(character) {
  if (selectedDetail.type === 'base') { const basic = section('人物設定'); bind(basic, 'ID', character, 'id'); bind(basic, '表示名', character, 'name'); bind(basic, '役割', character, 'role'); bind(basic, 'アイコン素材', character, 'icon'); bind(basic, '選択画面の背景', character, 'background'); bind(basic, '説明', character, 'description', true); condition(basic, '人物の表示条件', character.requires, (value) => { value ? character.requires = value : delete character.requires; mutate(); }); return [basic]; }
  const detail = section(selectedDetail.type === 'graph' ? (selectedDetail.graph.title || selectedDetail.graph.id) : `会話ノード：${selectedDetail.node.id || ''}`);
  if (selectedDetail.type === 'graph') renderConversation(selectedDetail.graph, detail);
  if (selectedDetail.type === 'node') renderConversationNode(selectedDetail.graph, selectedDetail.node, detail);
  return [detail];
}
function renderConversation(graph, parent) {
  const basic = section('会話グラフ'); bind(basic, '会話ID', graph, 'id'); bind(basic, 'タイトル（管理用）', graph, 'title'); bind(basic, '会話中の背景', graph, 'background'); condition(basic, '会話の表示条件', graph.requires, (value) => { value ? graph.requires = value : delete graph.requires; mutate(); }); eventLink(basic, '会話終了Event', graph, 'completionEventId');
  const repeat = document.createElement('label'); repeat.className = 'check-field'; const repeatBox = document.createElement('input'); repeatBox.type = 'checkbox'; repeatBox.checked = graph.repeatable === true; repeatBox.addEventListener('change', () => { repeatBox.checked ? graph.repeatable = true : delete graph.repeatable; mutate(); }); repeat.append(repeatBox, document.createTextNode(' 繰り返し可能')); basic.append(repeat);
  const nodes = graph.nodes || (graph.nodes = []); select(basic, '開始ノード', graph.startNodeId, [{ value: '', label: '選択してください' }, ...nodes.map((node) => ({ value: node.id, label: `${node.id}${node.text ? `：${node.text.slice(0, 30)}` : ''}` }))], (value) => { setOptional(graph, 'startNodeId', value); mutate(); }); parent.append(basic);
}
function renderConversationNode(graph, node, parent) {
  const card = section(`会話ノード：${node.id || ''}`); const nodes = graph.nodes || [];
  bind(card, 'ノードID', node, 'id'); select(card, '話者', node.speakerId || '', [{ value: '', label: '指定なし' }, { value: 'player', label: 'あなた（player）' }, { value: 'narrator', label: '説明（narrator）' }, ...(scenario.characters || []).map((c) => ({ value: c.id, label: `${c.name || c.id}（${c.id}）` }))], (value) => { setOptional(node, 'speakerId', value); mutate(); }); bind(card, 'アイコン素材（省略時は人物設定）', node, 'icon'); bind(card, '背景素材（省略時は既定背景）', node, 'background'); bind(card, 'セリフ・説明', node, 'text', true); condition(card, 'ノードの表示条件', node.requires, (value) => { value ? node.requires = value : delete node.requires; mutate(); }); eventLink(card, '全文表示後に起動するEvent', node, 'completionEventId');
  select(card, '次のノード', node.nextNodeId || '', [{ value: '', label: '指定なし（会話終了）' }, ...nodes.filter((x) => x !== node).map((x) => ({ value: x.id, label: x.id }))], (value) => { setOptional(node, 'nextNodeId', value); if (value) { delete node.choices; delete node.routes; } mutate(); }); renderChoices(card, node, nodes); renderRoutes(card, node, nodes); remove(card, () => { const index = nodes.indexOf(node); if (index >= 0) nodes.splice(index, 1); if (graph.startNodeId === node.id) delete graph.startNodeId; selectedDetail = { type: 'graph', graph }; mutate(); });
  parent.append(card);
}
function addConversation(character) { const graphs = character.interactions || (character.interactions = []); const n = graphs.length + 1; const graph = { id: `interaction_${character.id || 'character'}_${n}`, title: '新しい会話', startNodeId: 'node_001', nodes: [{ id: 'node_001', speakerId: character.id, text: '' }] }; graphs.push(graph); selectedDetail = { type: 'graph', graph }; mutate(); }
function addConversationNode(graph) { const nodes = graph.nodes || (graph.nodes = []); const n = nodes.length + 1; const node = { id: `node_${String(n).padStart(3, '0')}`, speakerId: '', text: '' }; nodes.push(node); if (!graph.startNodeId) graph.startNodeId = node.id; selectedDetail = { type: 'node', graph, node }; mutate(); }
function renderChoices(parent, node, nodes) { const box = section('選択肢'); const list = node.choices || []; list.forEach((choice, index) => { const row = document.createElement('div'); row.className = 'nested-card'; const order = document.createElement('div'); order.className = 'order-row'; const label = document.createElement('strong'); label.textContent = choice.text || choice.id || `選択肢 ${index + 1}`; order.append(label); orderButtons(order, list, index); row.append(order); bind(row, '選択肢ID', choice, 'id'); bind(row, '選択肢本文', choice, 'text', true); select(row, '遷移先', choice.nextNodeId || '', [{ value: '', label: '選択してください' }, ...nodes.map((n) => ({ value: n.id, label: n.id }))], (value) => { setOptional(choice, 'nextNodeId', value); mutate(); }); condition(row, '選択肢の表示条件', choice.requires, (value) => { value ? choice.requires = value : delete choice.requires; mutate(); }); eventLink(row, '選択時に起動するEvent', choice, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '選択肢を追加'; add.addEventListener('click', () => { node.choices = list; list.push({ id: `choice_${node.id || 'node'}_${list.length + 1}`, text: '' }); delete node.nextNodeId; delete node.routes; mutate(); }); box.append(add); parent.append(box); }
function renderRoutes(parent, node, nodes) { const box = section('条件による自動分岐（分岐専用の空ノード）'); const list = node.routes || []; list.forEach((route, index) => { const row = document.createElement('div'); row.className = 'nested-card'; condition(row, '分岐条件（上から評価）', route.requires, (value) => { value ? route.requires = value : delete route.requires; mutate(); }); select(row, '次のノード', route.nextNodeId || '', [{ value: '', label: '選択してください' }, ...nodes.filter((n) => n !== node).map((n) => ({ value: n.id, label: n.id }))], (value) => { setOptional(route, 'nextNodeId', value); mutate(); }); bind(row, '次の会話ID（別の会話へ移る場合）', route, 'nextConversationId'); eventLink(row, '分岐後に起動するEvent', route, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '分岐を追加'; add.addEventListener('click', () => { node.routes = list; list.push({ nextNodeId: '' }); delete node.nextNodeId; delete node.choices; mutate(); }); box.append(add); parent.append(box); }
function renderSimple(item, collection) {
  const basic = section('基本情報'); bind(basic, 'ID', item, 'id'); if (collection !== 'events') bind(basic, collection === 'hints' ? '対象ID' : '表示名', item, collection === 'hints' ? 'targetId' : 'name');
  if (collection === 'characters') { bind(basic, 'アイコン素材', item, 'icon'); bind(basic, '選択画面の背景', item, 'background'); bind(basic, '役割', item, 'role'); bind(basic, '説明', item, 'description', true); condition(basic, '人物の表示条件', item.requires, (value) => { value ? item.requires = value : delete item.requires; mutate(); }); }
  if (collection === 'evidence') { bind(basic, 'アイコン素材', item, 'icon'); bind(basic, '選択画面の背景', item, 'background'); bind(basic, '説明', item, 'description', true); if (selectedDetail.type === 'investigation') renderInvestigationDetail(selectedDetail.entry, basic); }
  if (collection === 'logs') { bind(basic, '選択画面の背景', item, 'background'); bind(basic, '説明', item, 'description', true); if (selectedDetail.type === 'logRow') renderLogRowDetail(item, selectedDetail.entry, basic); }
  if (collection === 'facts') { bind(basic, '説明', item, 'description', true); bind(basic, '表示順', item, 'sortOrder', false, 'number'); }
  if (collection === 'events') { delete item.trigger; condition(basic, '起動条件（省略すると常に実行）', item.requires, (value) => { value ? item.requires = value : delete item.requires; mutate(); }); renderEffects(item, basic); }
  if (collection === 'hints') renderStages(item, basic);
  return [basic];
}
function renderInvestigations(item, parent) { const box = section('調査項目'); const list = item.investigations || (item.investigations = []); list.forEach((entry, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, 'ID', entry, 'id'); bind(row, '表示名', entry, 'label'); bind(row, '説明', entry, 'description', true); eventLink(row, '調査完了Event', entry, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '調査項目を追加'; add.addEventListener('click', () => { list.push({ id: `investigation_${item.id}_${list.length + 1}`, label: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderRows(item, parent) { const box = section('ログ行'); const list = item.rows || (item.rows = []); list.forEach((row, index) => { const card = document.createElement('div'); card.className = 'nested-card'; bind(card, 'ID', row, 'id'); bind(card, '時刻', row, 'time'); bind(card, '本文（改行可）', row, 'text', true); eventLink(card, '調査完了Event', row, 'completionEventId'); const check = document.createElement('label'); check.className = 'check-field'; const input = document.createElement('input'); input.type = 'checkbox'; input.checked = Boolean(row.important); input.addEventListener('change', () => { input.checked ? row.important = true : delete row.important; mutate(); }); check.append(input, document.createTextNode(' 調査できる行（？を表示）')); card.append(check); bind(card, '調査結果', row, 'result', true); remove(card, () => { list.splice(index, 1); mutate(); }); box.append(card); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'ログ行を追加'; add.addEventListener('click', () => { list.push({ id: `row_${item.id}_${list.length + 1}`, text: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderInvestigationDetail(entry, parent) { const box = section('証拠品調査項目'); bind(box, 'ID', entry, 'id'); bind(box, '表示名', entry, 'label'); bind(box, '説明', entry, 'description', true); eventLink(box, '調査完了Event', entry, 'completionEventId'); remove(box, () => { const item = scenario.evidence[selectedIndex]; const list = item.investigations || []; const index = list.indexOf(entry); if (index >= 0) list.splice(index, 1); selectedDetail = { type: 'base' }; mutate(); }); parent.append(box); }
function renderLogRowDetail(item, entry, parent) { const box = section('ログ行'); const list = item.rows || []; bind(box, 'ID', entry, 'id'); bind(box, '時刻', entry, 'time'); bind(box, '本文（改行可）', entry, 'text', true); eventLink(box, '調査完了Event', entry, 'completionEventId'); const check = document.createElement('label'); check.className = 'check-field'; const input = document.createElement('input'); input.type = 'checkbox'; input.checked = Boolean(entry.important); input.addEventListener('change', () => { input.checked ? entry.important = true : delete entry.important; mutate(); }); check.append(input, document.createTextNode(' 調査できる行（？を表示）')); box.append(check); bind(box, '調査結果', entry, 'result', true); remove(box, () => { const index = list.indexOf(entry); if (index >= 0) list.splice(index, 1); selectedDetail = { type: 'base' }; mutate(); }); parent.append(box); }
function renderEffects(item, parent) { const box = section('Effect'); const list = item.effects || (item.effects = []); const targets = ['evidence', 'logs', 'facts', 'usedHints'].flatMap((kind) => (scenario[kind] || []).map((entry) => ({ value: `${kind}.${entry.id}`, label: `${kind}：${entry.name || entry.title || entry.id}` }))); list.forEach((effect, index) => { const row = document.createElement('div'); row.className = 'nested-card'; select(row, '種類', effect.type || 'add', [{ value: 'add', label: '追加' }, { value: 'remove', label: '削除' }, { value: 'set', label: '状態を設定' }], (value) => { effect.type = value; if (value === 'set') effect.target = 'cleared'; mutate(); }); if (effect.type === 'set') { select(row, '設定項目', effect.target || 'cleared', [{ value: 'cleared', label: 'ゲームクリア状態' }], (value) => { effect.target = value; mutate(); }); select(row, '値', String(effect.value), [{ value: 'true', label: '有効' }, { value: 'false', label: '無効' }], (value) => { effect.value = value === 'true'; mutate(); }); } else select(row, '対象', effect.target || '', [{ value: '', label: '選択してください' }, ...targets], (value) => { setOptional(effect, 'target', value); mutate(); }); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'Effectを追加'; add.addEventListener('click', () => { list.push({ type: 'add', target: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderStages(item, parent) { const box = section('ヒント段階'); const list = item.stages || (item.stages = []); list.forEach((stage, index) => { const row = document.createElement('div'); row.className = 'nested-card'; bind(row, 'ID', stage, 'id'); bind(row, '本文', stage, 'text', true); eventLink(row, '提示完了Event', stage, 'completionEventId'); remove(row, () => { list.splice(index, 1); mutate(); }); box.append(row); }); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '段階を追加'; add.addEventListener('click', () => { list.push({ id: `hint_${item.id}_${list.length + 1}`, text: '' }); mutate(); }); box.append(add); parent.append(box); }
function renderTabs() { ui.tabs.replaceChildren(); Object.entries(COLLECTIONS).forEach(([key, config]) => { const button = document.createElement('button'); button.type = 'button'; button.className = `tab${key === activeCollection ? ' is-active' : ''}`; button.textContent = config.label; button.addEventListener('click', () => { activeCollection = key; selectedIndex = -1; selectedDetail = { type: 'base' }; renderTabs(); renderList(); renderOutline(); renderEditor(); }); ui.tabs.append(button); }); ui.collectionTitle.textContent = COLLECTIONS[activeCollection].label; }
function renderList() { const items = scenario[activeCollection] || []; ui.count.textContent = items.length; ui.list.replaceChildren(); items.forEach((item, index) => { const button = document.createElement('button'); button.type = 'button'; button.className = `entry${index === selectedIndex ? ' is-active' : ''}`; button.textContent = item.name || item.title || item.id; button.addEventListener('click', () => { selectedIndex = index; selectedDetail = { type: 'base' }; renderList(); renderOutline(); renderEditor(); }); ui.list.append(button); }); }
function outlineButton(label, active, callback, items, index, indent = 0) { const row = document.createElement('div'); row.className = `outline-row${indent ? ' is-indented' : ''}`; const button = document.createElement('button'); button.type = 'button'; button.className = `outline-entry${active ? ' is-active' : ''}`; button.textContent = label || '（名前なし）'; button.addEventListener('click', callback); row.append(button); if (items) orderButtons(row, items, index); ui.outline.append(row); return row; }
function outlineNodeButton(node, nodes, index, active, callback) {
  const row = document.createElement('div'); row.className = 'outline-row is-indented node-outline-row';
  const button = document.createElement('button'); button.type = 'button'; button.className = `outline-entry node-outline-entry${active ? ' is-active' : ''}`;
  const heading = document.createElement('span'); heading.className = 'node-outline-heading';
  const id = document.createElement('strong'); id.textContent = node.id || '会話ノード'; heading.append(id);
  const speaker = document.createElement('span'); speaker.className = 'node-outline-speaker';
  const speakerId = node.speakerId; const character = (scenario.characters || []).find((entry) => entry.id === speakerId);
  speaker.textContent = speakerId === 'player' ? 'あなた' : speakerId === 'narrator' ? '説明' : character ? (character.name || character.id) : speakerId || '話者未設定';
  heading.append(speaker); button.append(heading);
  const dialogue = document.createElement('span'); dialogue.className = 'node-outline-text'; dialogue.textContent = node.text || '（セリフなし）'; button.append(dialogue);
  if (node.choices?.length) {
    const choices = document.createElement('span'); choices.className = 'node-outline-choices';
    const label = document.createElement('span'); label.className = 'node-outline-choices-label'; label.textContent = '選択肢'; choices.append(label);
    for (const choice of node.choices) { const line = document.createElement('span'); line.className = 'node-outline-choice'; line.textContent = `・${choice.text || choice.id || '（本文なし）'}`; choices.append(line); }
    button.append(choices);
  }
  button.addEventListener('click', callback); row.append(button); orderButtons(row, nodes, index); ui.outline.append(row); return row;
}
function renderOutline() {
  ui.outline.replaceChildren(); ui.outlineTitle.textContent = COLLECTIONS[activeCollection].label; const item = (scenario[activeCollection] || [])[selectedIndex];
  if (!item) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '左の一覧から項目を選択してください。'; ui.outline.append(empty); return; }
  const choose = (detail) => { selectedDetail = detail; renderOutline(); renderEditor(); };
  if (activeCollection === 'characters') {
    outlineButton(item.name || item.id, selectedDetail.type === 'base', () => choose({ type: 'base' }));
    for (const graph of item.interactions || []) { const graphRow = outlineButton(graph.title || graph.id, selectedDetail.graph === graph, () => choose({ type: 'graph', graph }), null, 0, 1); const deleteGraph = document.createElement('button'); deleteGraph.type = 'button'; deleteGraph.className = 'button danger order-button'; deleteGraph.textContent = '×'; deleteGraph.setAttribute('aria-label', '会話を削除'); deleteGraph.addEventListener('click', () => { item.interactions.splice(item.interactions.indexOf(graph), 1); selectedDetail = { type: 'base' }; mutate(); }); graphRow.append(deleteGraph); for (const node of graph.nodes || []) { const nodes = graph.nodes; const index = nodes.indexOf(node); outlineNodeButton(node, nodes, index, selectedDetail.node === node, () => choose({ type: 'node', graph, node })); } }
    const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '会話を追加'; add.addEventListener('click', () => addConversation(item)); ui.outline.append(add);
    if (selectedDetail.type === 'graph') { const addNode = document.createElement('button'); addNode.type = 'button'; addNode.className = 'button secondary'; addNode.textContent = 'ノードを追加'; addNode.addEventListener('click', () => addConversationNode(selectedDetail.graph)); ui.outline.append(addNode); }
    return;
  }
  if (activeCollection === 'evidence') { outlineButton(item.name || item.id, selectedDetail.type === 'base', () => choose({ type: 'base' })); for (const entry of item.investigations || []) outlineButton(entry.label || entry.id, selectedDetail.entry === entry, () => choose({ type: 'investigation', entry }), null, 0, 1); const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = '調査項目を追加'; add.addEventListener('click', () => { const list = item.investigations || (item.investigations = []); const entry = { id: `investigation_${item.id}_${list.length + 1}`, label: '' }; list.push(entry); selectedDetail = { type: 'investigation', entry }; mutate(); }); ui.outline.append(add); return; }
  if (activeCollection === 'logs') { outlineButton(item.name || item.id, selectedDetail.type === 'base', () => choose({ type: 'base' })); for (const entry of item.rows || []) { const rows = item.rows; outlineButton(entry.text || entry.id, selectedDetail.entry === entry, () => choose({ type: 'logRow', entry }), rows, rows.indexOf(entry), 1); } const add = document.createElement('button'); add.type = 'button'; add.className = 'button secondary'; add.textContent = 'ログ行を追加'; add.addEventListener('click', () => { const rows = item.rows || (item.rows = []); const entry = { id: `row_${item.id}_${rows.length + 1}`, text: '' }; rows.push(entry); selectedDetail = { type: 'logRow', entry }; mutate(); }); ui.outline.append(add); return; }
  outlineButton(item.name || item.title || item.id, true, () => choose({ type: 'base' }));
}
function renderEditor() { const item = (scenario[activeCollection] || [])[selectedIndex]; ui.fields.replaceChildren(); $('#delete-button').hidden = !item || selectedDetail.type !== 'base'; if (!item) { ui.title.textContent = '項目を選択してください'; ui.fields.innerHTML = '<div class="empty">左の一覧から項目を選ぶか、新しい項目を追加してください。</div>'; return; } ui.title.textContent = selectedDetail.type === 'graph' ? (selectedDetail.graph.title || selectedDetail.graph.id) : selectedDetail.type === 'node' ? (selectedDetail.node.id || '会話ノード') : selectedDetail.type === 'investigation' ? (selectedDetail.entry.label || selectedDetail.entry.id) : selectedDetail.type === 'logRow' ? (selectedDetail.entry.text || selectedDetail.entry.id) : item.name || item.title || item.id; try { const sections = activeCollection === 'characters' ? renderCharacter(item) : renderSimple(item, activeCollection); sections.forEach((entry) => ui.fields.append(entry)); } catch (error) { const message = document.createElement('div'); message.className = 'empty'; message.textContent = `編集欄の描画に失敗しました: ${error.message}`; ui.fields.append(message); console.error(error); } }
function renderPreview() { ui.preview.textContent = JSON.stringify(scenario, null, 2); }
function validateScenario() {
  const errors = []; const warnings = []; if (!scenario.id?.trim()) errors.push('事件IDが空です'); if (!scenario.title?.trim()) errors.push('事件名が空です');
  const ids = new Map(); const addId = (id, label) => { if (!id) errors.push(`${label}のIDがありません`); else if (ids.has(id)) errors.push(`ID「${id}」が重複しています（${ids.get(id)} / ${label}）`); else ids.set(id, label); };
  for (const [key, config] of Object.entries(COLLECTIONS)) for (const [index, item] of (scenario[key] || []).entries()) { addId(item?.id, `${config.label} ${index + 1}`); if (key !== 'events' && !item.name && !item.title && key !== 'hints') errors.push(`${config.label}「${item.id || index + 1}」の表示名がありません`); }
  const graphTargets = new Set();
  for (const { character, graph } of allInteractions()) {
    addId(graph.id, `会話グラフ（${character.name || character.id}）`); graphTargets.add(graph.id); const nodes = new Set((graph.nodes || []).map((node) => node.id));
    if (!graph.startNodeId || !nodes.has(graph.startNodeId)) errors.push(`会話「${graph.id}」の開始ノードがありません`); if (nodes.size !== (graph.nodes || []).length) errors.push(`会話「${graph.id}」内でノードIDが重複しています`);
    for (const node of graph.nodes || []) {
      if (!node.id) errors.push(`会話「${graph.id}」にIDのないノードがあります`);
      const refs = [node.nextNodeId, ...(node.choices || []).map((choice) => choice.nextNodeId), ...(node.routes || []).map((route) => route.nextNodeId)].filter(Boolean); refs.forEach((ref) => { if (!nodes.has(ref)) errors.push(`ノード「${node.id}」の遷移先「${ref}」がありません`); });
      for (const choice of node.choices || []) { if (choice.id) { addId(choice.id, `選択肢（${node.id}）`); } else warnings.push(`ノード「${node.id}」の選択肢にIDがありません`); }
      if (node.routes?.length && (node.text || node.speakerId || node.choices || node.nextNodeId)) warnings.push(`分岐専用ノード「${node.id}」には本文・話者・通常遷移を設定しないでください`);
    }
  }
  for (const evidence of scenario.evidence || []) for (const item of evidence.investigations || []) { addId(item.id, '証拠調査'); }
  for (const log of scenario.logs || []) for (const row of log.rows || []) { addId(row.id, 'ログ行'); }
  for (const hint of scenario.hints || []) for (const stage of hint.stages || []) { addId(stage.id, 'ヒント段階'); }
  for (const item of [...(scenario.evidence || []), ...(scenario.logs || []), ...(scenario.hints || []), ...(scenario.events || []), ...allInteractions().map((x) => x.graph)]) for (const cond of [item.requires]) if (cond?.type === 'conversation' && cond.targetId && !graphTargets.has(cond.targetId)) errors.push(`条件の会話「${cond.targetId}」が見つかりません`);
  if (scenario.conversations?.length) errors.push('旧形式の最上位 conversations が残っています。人物の interactions[] へ移行してください');
  return { errors, warnings };
}
function renderValidation() { const { errors, warnings } = validateScenario(); ui.validation.replaceChildren(); if (!errors.length && !warnings.length) { const li = document.createElement('li'); li.className = 'ok'; li.textContent = 'エラーはありません。人物内会話グラフと参照を確認しました。'; ui.validation.append(li); return; } [...errors, ...warnings].forEach((message) => { const li = document.createElement('li'); li.className = errors.includes(message) ? 'error' : ''; li.textContent = `${errors.includes(message) ? 'エラー' : '確認'}：${message}`; ui.validation.append(li); }); }
function normalizeScenario(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('JSONの最上位はオブジェクトにしてください');
  for (const [key, config] of Object.entries(COLLECTIONS)) if (!Array.isArray(input[key])) input[key] = [];
  // 旧メーカー形式を読み込んだ場合は、最初の非player/narrator話者を持つ人物に会話グラフを移す。
  if (Array.isArray(input.conversations)) { for (const graph of input.conversations) { const speaker = (graph.nodes || []).map((node) => node.speakerId).find((id) => id && !['player', 'narrator'].includes(id)); const owner = input.characters.find((character) => character.id === speaker) || input.characters[0]; if (owner) { owner.interactions ||= []; owner.interactions.push(graph); } } delete input.conversations; }
  for (const character of input.characters) { character.interactions ||= []; for (const graph of character.interactions) for (const node of graph.nodes || []) for (const [index, choice] of (node.choices || []).entries()) choice.id ||= `choice_${graph.id}_${node.id}_${index + 1}`; }
  for (const event of input.events) delete event.trigger;
  input.schemaVersion ||= 1; if (!input.defaults || typeof input.defaults !== 'object' || Array.isArray(input.defaults)) input.defaults = {}; return input;
}
function addItem() { const config = COLLECTIONS[activeCollection]; const index = (scenario[activeCollection] || []).length + 1; const item = { id: `${config.prefix}_new_${String(index).padStart(3, '0')}` }; if (activeCollection === 'characters' || ['evidence', 'logs', 'facts'].includes(activeCollection)) item.name = `新しい${config.label}`; if (activeCollection === 'characters') item.interactions = []; if (activeCollection === 'events') item.effects = []; if (activeCollection === 'hints') item.stages = []; scenario[activeCollection].push(item); selectedIndex = scenario[activeCollection].length - 1; selectedDetail = { type: 'base' }; mutate(); }
function download() { const result = validateScenario(); if (result.errors.length) return toast(`エラー ${result.errors.length} 件を修正してください`); const blob = new Blob([`${JSON.stringify(scenario, null, 2)}\n`], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${scenario.id || 'scenario'}.json`; link.click(); URL.revokeObjectURL(link.href); toast('シナリオJSONを書き出しました'); }
async function loadFile(file) { try { scenario = normalizeScenario(parse(await file.text(), 'ファイル')); activeCollection = 'characters'; selectedIndex = -1; renderAll(); persist(); toast('人物内会話グラフ形式で読み込みました'); } catch (error) { toast(error.message); } }
function renderAll() { renderTabs(); renderList(); renderOutline(); renderEditor(); $('#case-id').value = scenario.id || ''; $('#case-title').value = scenario.title || ''; $('#case-defaults').value = JSON.stringify(scenario.defaults || {}, null, 2); renderPreview(); renderValidation(); }
ui.jsonOpen.addEventListener('click', () => { renderPreview(); ui.jsonDialog.showModal(); }); ui.jsonClose.addEventListener('click', () => ui.jsonDialog.close());
$('#case-id').addEventListener('input', (event) => { scenario.id = event.target.value; mutate(); }); $('#case-title').addEventListener('input', (event) => { scenario.title = event.target.value; mutate(); }); $('#case-defaults').addEventListener('change', (event) => { try { scenario.defaults = parse(event.target.value, '共通背景'); mutate(); } catch (error) { toast(error.message); } }); $('#add-button').addEventListener('click', addItem); $('#delete-button').addEventListener('click', () => { if (selectedIndex >= 0) { scenario[activeCollection].splice(selectedIndex, 1); selectedIndex = -1; selectedDetail = { type: 'base' }; mutate(); } }); $('#download-button').addEventListener('click', download); $('#validate-button').addEventListener('click', renderValidation); $('#file-input').addEventListener('change', (event) => { const file = event.target.files?.[0]; if (file) loadFile(file); event.target.value = ''; }); $('#copy-button').addEventListener('click', async () => { try { await navigator.clipboard.writeText(JSON.stringify(scenario, null, 2)); toast('JSONをコピーしました'); } catch { toast('コピーできません。JSONを選択してコピーしてください'); } });
async function start() { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { try { scenario = normalizeScenario(parse(saved, '保存データ')); } catch { scenario = blankScenario(); } } else { scenario = blankScenario(); const source = new URLSearchParams(location.search).get('source'); if (source) { try { const response = await fetch(`../${encodeURIComponent(source)}`); if (response.ok) scenario = normalizeScenario(await response.json()); } catch { /* ローカル起動時は空の編集画面を使う */ } } } scenario = normalizeScenario(scenario); renderAll(); persist(); }
start();
